{{- if .values.postgres.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database.postgres.pvc.name" . }}
  namespace: {{ .values.global.namespace }}
  labels:
    {{- include "database.postgres.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep   # survive helm uninstall — protect player data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .values.postgres.storage }}

{{- end }}