apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: {{ .Values.agonesConfig.fleet.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.agonesConfig.fleet.replicas }}
  template:
    spec:
      ports:
        - name: {{ .Values.agonesConfig.fleet.port.name }}
          containerPort: {{ .Values.agonesConfig.fleet.port.containerPort }}
      health:
        initialDelaySeconds: {{ .Values.agonesConfig.fleet.health.initialDelaySeconds }}
        periodSeconds: {{ .Values.agonesConfig.fleet.health.periodSeconds }}
        failureThreshold: {{ .Values.agonesConfig.fleet.health.failureThreshold }}
      template:
        spec:
          containers:
            - name: battle-server
              image: "{{ .Values.global.registry }}/{{ .Values.agonesConfig.fleet.image.repository }}:{{ .Values.agonesConfig.fleet.image.tag }}"
              imagePullPolicy: {{ .Values.global.imagePullPolicy }}
              env:
                - name: ASPNETCORE_HTTP_PORTS
                  value: "$(SIGNALR)"
                - name: DB_WRAPPER_URL
                  value: "http://{{ .Release.Name }}-service-database-wrapper.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.global.dbWrapperPort }}"
                - name: INTERNAL_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: auth-secret
                      key: internal-api-key
                - name: JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: auth-secret
                      key: jwt-secret
                - name: JWT_ISSUER
                  valueFrom:
                    secretKeyRef:
                      name: auth-secret
                      key: jwt-issuer
                - name: JWT_AUDIENCE
                  valueFrom:
                    secretKeyRef:
                      name: auth-secret
                      key: jwt-audience
              resources:
                {{- toYaml .Values.agonesConfig.fleet.resources | nindent 16 }}
