
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "database.ingress.name" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  entryPoints:
    {{- if .Values.global.ingress.tls.enabled }}
    - websecure
    {{- else }}
    - web
    {{- end }}

  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}

  routes:
    - match: Host(`{{ .Values.global.ingress.host }}`) && PathPrefix(`/api/db`)
      kind: Rule
      middlewares:
        - name: {{ include "database.middleware.strip" . }}
      services:
        - name: {{ include "database.wrapper.service.name" . }}
          port: {{ .Values.dbWrapper.service.port }}
