apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "matchmaking.ingress.name" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  entryPoints:
    {{- if .Values.global.ingress.tls.enabled }}
    - websecure
    {{- else }}
    - web
    {{- end }}

  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}

  routes:
    - match: (Host(`{{ .Values.global.ingress.host }}`) || Host(`https://disclose-recital-aversion.ngrok-free.dev`)) && PathPrefix(`/api/mm`)
      kind: Rule
      middlewares:
        - name: {{ include "matchmaking.middleware.strip" . }}
      services:
        - name: {{ include "matchmaking.service.name" . }}
          port: {{ .Values.matchmaking.service.port }}
