apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "database.wrapper.deployment.name" . }}
  namespace: {{ .values.global.namespace}}
  labels:
    {{- include "database.wrapper.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "database.wrapper.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "database.wrapper.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .values.dbWrapper.name }}
          image: {{ include "database.wrapper.image" . }}
          imagePullPolicy: {{ .values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .values.dbWrapper.service.port }}
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .values.dbWrapper.service.port }}"
            - name: DB_HOST
              value: {{ include "database.postgres.service.name" . }}
            - name: DB_PORT
              value: {{ .values.postgres.port }}
            - name: DB_NAME
              value: {{ .values.postgres.name }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .values.dbsecret.name }}
                  key: {{ .values.dbsecret.usernameKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .values.dbsecret.name }}
                  key: {{ .values.dbsecret.passwordKey }}
          resources:
            requests:
              cpu: {{ .values.dbWrapper.resources.requests.cpu | quote }}
              memory: {{ .values.dbWrapper.resources.requests.memory | quote }}
            limits:
              cpu: {{ .values.dbWrapper.resources.limits.cpu | quote }}
              memory: {{ .values.dbWrapper.resources.limits.memory | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .values.dbWrapper.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5