apiVersion: v1
kind: Service
metadata:
  name: {{- include "database.wrapper.service.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "database.labels.wrapper" . | nindent 4 }}
spec:
  selector:
    {{- include "database.labels.wrapper" . | nindent 4 }}
  ports:
    - port: {{ .Values.dbWrapper.service.port }}
      targetPort: {{ .Values.dbWrapper.service.port }}
  type: ClusterIP