apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authsecret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "database.wrapper.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.authsecret.jwtSecretKey }}: {{ .Values.authsecret.jwtSecret | quote }}
  {{ .Values.authsecret.jwtIssuerKey }}: {{ .Values.authsecret.jwtIssuer | quote }}
  {{ .Values.authsecret.jwtAudienceKey }}: {{ .Values.authsecret.jwtAudience | quote }}
  {{ .Values.authsecret.internalApiKeyKey }}: {{ .Values.authsecret.internalApiKey | quote }}
