global:
  registry: ad04a
  imagePullPolicy: Always
  namespace: db-wrapper

ingress:
  host: localhost         # CHANGE to your real domain
  tls:
    enabled: false
    secretName: game-tls
    certManager:
      enabled: false
      issuerName: letsencrypt-prod
      issuerKind: ClusterIssuer
  adminCidr:
    - "10.0.0.0/8"   

dbsecret:
  name: postgres-secret
  usernameKey: username
  passwordKey: password 
  username: ""
  password: ""


dbWrapper:
  name: database-wrapper
  image:
    repository: primal-conquest-db-wrapper
    tag: latest
  service:
    port: 5000
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"



postgres:
  enabled: true
  port: "5432"
  name: gamedb
  image: postgres:18-alpine
  storage: 500Mi
  service:
    name: postgres-svc
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"