global:
  imagePullPolicy: Always
 
ingress:
  host: 178.105.78.86         # CHANGE to your real domain
  tls:
    enabled: false
    secretName: game-tls
    certManager:
      enabled: false
      issuerName: letsencrypt-prod
      issuerKind: ClusterIssuer
                    # internal VPN/cluster only — no localhost
 
agonesConfig:
  fleet:
    replicas: 4
  autoscaler:
    bufferSize: 4
    minReplicas: 4
    maxReplicas: 100
 
database:
  authsecret:
    jwtSecret: ""          # FILL IN — inject via CI secret or: helm upgrade ... --set database.authsecret.jwtSecret=$JWT_SECRET
    internalApiKey: ""     # FILL IN — inject via CI secret or: helm upgrade ... --set database.authsecret.internalApiKey=$INTERNAL_KEY
  dwWrapper:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  postgres:
    storage: 20Gi
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
 
matchmaking:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
